"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: 0209794dca2b
Revises: 732c63439203
Create Date: 2025-12-11 02:05:27.101108

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0209794dca2b"
down_revision: str | None = "732c63439203"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rehearsal_scenes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rehearsal_id", sa.Uuid(), nullable=False),
        sa.Column("scene_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rehearsal_id"],
            ["rehearsals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scenes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rehearsal_id", "scene_id", name="uq_rehearsal_scene"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rehearsal_scenes")
    # ### end Alembic commands ###
