"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: 11398f069793
Revises: ce7cc9d0b71f
Create Date: 2026-03-21 14:28:21.909932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11398f069793'
down_revision: Union[str, None] = 'ce7cc9d0b71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_events', sa.Column('reminder_3_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('theater_projects', sa.Column('attendance_reminder_3_hours', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theater_projects', 'attendance_reminder_3_hours')
    op.drop_column('attendance_events', 'reminder_3_sent_at')
    # ### end Alembic commands ###
