"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: 26dcbb9f2c36
Revises: acb265c6599f
Create Date: 2025-12-09 18:18:09.306054

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '26dcbb9f2c36'
down_revision: str | None = 'acb265c6599f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('location', sa.String(length=200), nullable=True))
    op.alter_column('milestones', 'color',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=7),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('milestones', 'color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('milestones', 'location')
    # ### end Alembic commands ###
