"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: 3319a4c48ed0
Revises: 8d9a40f8cd8a
Create Date: 2025-12-08 02:14:37.847344

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3319a4c48ed0'
down_revision: str | None = '8d9a40f8cd8a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('default_staff_role', sa.String(length=100), nullable=True))
    op.add_column('rehearsal_participants', sa.Column('staff_role', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rehearsal_participants', 'staff_role')
    op.drop_column('project_members', 'default_staff_role')
    # ### end Alembic commands ###
