"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: 4880a38c039a
Revises: d840552faeb6
Create Date: 2025-12-12 23:18:50.872924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4880a38c039a'
down_revision: Union[str, None] = 'd840552faeb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theater_projects', sa.Column('discord_script_webhook_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theater_projects', 'discord_script_webhook_url')
    # ### end Alembic commands ###
