"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: 52a71fe9ab75
Revises: 15edb111ec4c
Create Date: 2026-02-25 21:21:05.743333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a71fe9ab75'
down_revision: Union[str, None] = '15edb111ec4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_polls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('message_id', sa.String(length=50), nullable=True),
    sa.Column('channel_id', sa.String(length=50), nullable=True),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['theater_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_poll_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('poll_id', sa.Uuid(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['schedule_polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_poll_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['schedule_poll_candidates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'user_id', name='uq_poll_candidate_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_poll_answers')
    op.drop_table('schedule_poll_candidates')
    op.drop_table('schedule_polls')
    # ### end Alembic commands ###
