"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: 5b43ac2a01b2
Revises: ab416aca0cee
Create Date: 2025-12-08 00:10:32.782503

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5b43ac2a01b2'
down_revision: str | None = 'ab416aca0cee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('act_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'act_number')
    # ### end Alembic commands ###
