"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: 6c5e9f1b0458
Revises: 79e8e3d948f5
Create Date: 2026-03-01 03:43:25.137787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c5e9f1b0458'
down_revision: Union[str, None] = '79e8e3d948f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_events') as batch_op:
        batch_op.add_column(sa.Column('reminder_1_sent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('reminder_2_sent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('reminder_sent_at')
        
    with op.batch_alter_table('theater_projects') as batch_op:
        batch_op.add_column(sa.Column('attendance_reminder_1_hours', sa.Integer(), server_default=sa.text('48'), nullable=False))
        batch_op.add_column(sa.Column('attendance_reminder_2_hours', sa.Integer(), server_default=sa.text('24'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theater_projects') as batch_op:
        batch_op.drop_column('attendance_reminder_2_hours')
        batch_op.drop_column('attendance_reminder_1_hours')
        
    with op.batch_alter_table('attendance_events') as batch_op:
        batch_op.add_column(sa.Column('reminder_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_column('reminder_2_sent_at')
        batch_op.drop_column('reminder_1_sent_at')
    # ### end Alembic commands ###
