"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: 71fdf49aabc4
Revises: d28bee5388f7
Create Date: 2026-03-09 00:52:37.774835

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71fdf49aabc4"
down_revision: str | None = "d28bee5388f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scripts",
        sa.Column(
            "pdf_orientation", sa.String(length=20), server_default="landscape", nullable=False
        ),
    )
    op.add_column(
        "scripts",
        sa.Column(
            "pdf_writing_direction", sa.String(length=20), server_default="vertical", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scripts", "pdf_writing_direction")
    op.drop_column("scripts", "pdf_orientation")
    # ### end Alembic commands ###
