"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: 79e8e3d948f5
Revises: a97dfcebc4e8
Create Date: 2026-03-01 01:36:56.583141

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79e8e3d948f5"
down_revision: str | None = "a97dfcebc4e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("theater_projects", sa.Column("created_by_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        None, "theater_projects", "users", ["created_by_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "theater_projects", type_="foreignkey")
    op.drop_column("theater_projects", "created_by_id")
    # ### end Alembic commands ###
