"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: 7a09c18189f8
Revises: 6c5e9f1b0458
Create Date: 2026-03-08 22:58:18.353018

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a09c18189f8"
down_revision: str | None = "6c5e9f1b0458"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule_polls", sa.Column("deadline", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "schedule_polls", sa.Column("reminder_sent_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "schedule_polls",
        sa.Column(
            "auto_reminder_stopped", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule_polls", "auto_reminder_stopped")
    op.drop_column("schedule_polls", "reminder_sent_at")
    op.drop_column("schedule_polls", "deadline")
    # ### end Alembic commands ###
