"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: 8556f52c33e9
Revises: 11398f069793
Create Date: 2026-03-26 16:31:00.109755

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8556f52c33e9'
down_revision: str | None = '11398f069793'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('is_custom', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('scene_character_mappings', sa.Column('is_manual', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('scenes', sa.Column('is_custom', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'is_custom')
    op.drop_column('scene_character_mappings', 'is_manual')
    op.drop_column('characters', 'is_custom')
    # ### end Alembic commands ###
