"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: 8d9a40f8cd8a
Revises: 5b43ac2a01b2
Create Date: 2025-12-08 00:56:47.152839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9a40f8cd8a'
down_revision: Union[str, None] = '5b43ac2a01b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('revision', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'revision')
    # ### end Alembic commands ###
