"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: 8d9a40f8cd8a
Revises: 5b43ac2a01b2
Create Date: 2025-12-08 00:56:47.152839

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d9a40f8cd8a'
down_revision: str | None = '5b43ac2a01b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('revision', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'revision')
    # ### end Alembic commands ###
