"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: a97dfcebc4e8
Revises: 52a71fe9ab75
Create Date: 2026-03-01 01:29:10.791673

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a97dfcebc4e8"
down_revision: str | None = "52a71fe9ab75"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("premium_password", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "premium_password")
    # ### end Alembic commands ###
