"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: ab416aca0cee
Revises: b2b3ca1feb2f
Create Date: 2025-12-06 23:52:03.999272

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ab416aca0cee'
down_revision: str | None = 'b2b3ca1feb2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theater_projects', sa.Column('discord_webhook_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theater_projects', 'discord_webhook_url')
    # ### end Alembic commands ###
