"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: ab6eb8af6b2b
Revises: 71fdf49aabc4
Create Date: 2026-03-09 01:19:29.812653

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab6eb8af6b2b"
down_revision: str | None = "71fdf49aabc4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters", sa.Column("order", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "order")
    # ### end Alembic commands ###
