"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: acb265c6599f
Revises: a97a9d567b99
Create Date: 2025-12-09 17:59:51.244876

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'acb265c6599f'
down_revision: str | None = 'a97a9d567b99'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
