"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: c0e567c6f687
Revises: 3319a4c48ed0
Create Date: 2025-12-08 16:00:52.805577

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c0e567c6f687'
down_revision: str | None = '3319a4c48ed0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
