"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: d840552faeb6
Revises: ffcb638b644a
Create Date: 2025-12-12 22:45:52.341858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd840552faeb6'
down_revision: Union[str, None] = 'ffcb638b644a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'description')
    # ### end Alembic commands ###
