"""Add screen_name and discord_avatar_hash to User

Revision ID: e3f4a5b6c7d8
Revises: 732c63439203
Create Date: 2025-12-11 10:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f4a5b6c7d8'
down_revision: Union[str, None] = '732c63439203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('screen_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('discord_avatar_hash', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'discord_avatar_hash')
    op.drop_column('users', 'screen_name')
    # ### end Alembic commands ###
