"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: e44101c53df8
Revises: 4880a38c039a
Create Date: 2025-12-13 01:04:15.635919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44101c53df8'
down_revision: Union[str, None] = '4880a38c039a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_events', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_events', 'reminder_sent_at')
    # ### end Alembic commands ###
