"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: e44101c53df8
Revises: 4880a38c039a
Create Date: 2025-12-13 01:04:15.635919

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e44101c53df8"
down_revision: str | None = "4880a38c039a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attendance_events",
        sa.Column("reminder_sent_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attendance_events", "reminder_sent_at")
    # ### end Alembic commands ###
