"""Alembicマイグレーションスクリプトテンプレート.

Revision ID: ffcb638b644a
Revises: f198a55771bf
Create Date: 2025-12-12 22:18:54.487271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffcb638b644a'
down_revision: Union[str, None] = 'f198a55771bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """アップグレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lines', 'character_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """ダウングレードマイグレーション."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('lines', 'character_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
